# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'U-Net.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1153, 878)
        MainWindow.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_title_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_title_4.setFont(font)
        self.label_title_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 28pt \"Agency FB\";")
        self.label_title_4.setObjectName("label_title_4")
        self.verticalLayout_12.addWidget(self.label_title_4, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.verticalLayout_12)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_23.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem1)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_imNum_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_imNum_10.setFont(font)
        self.label_imNum_10.setObjectName("label_imNum_10")
        self.verticalLayout_15.addWidget(self.label_imNum_10)
        self.label_i_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_i_10.setFont(font)
        self.label_i_10.setObjectName("label_i_10")
        self.verticalLayout_15.addWidget(self.label_i_10)
        self.label_res_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_res_10.setFont(font)
        self.label_res_10.setObjectName("label_res_10")
        self.verticalLayout_15.addWidget(self.label_res_10)
        self.horizontalLayout_23.addLayout(self.verticalLayout_15)
        self.horizontalLayout_23.setStretch(0, 20)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_23.setStretch(2, 8)
        self.verticalLayout.addLayout(self.horizontalLayout_23)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushBt_up_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushBt_up_10.setFont(font)
        self.pushBt_up_10.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.pushBt_up_10.setObjectName("pushBt_up_10")
        self.horizontalLayout_24.addWidget(self.pushBt_up_10)
        self.pushBt_dwn_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushBt_dwn_10.setFont(font)
        self.pushBt_dwn_10.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"background-color: rgb(168, 168, 168);")
        self.pushBt_dwn_10.setObjectName("pushBt_dwn_10")
        self.horizontalLayout_24.addWidget(self.pushBt_dwn_10)
        self.pushBt_reset_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushBt_reset_10.setFont(font)
        self.pushBt_reset_10.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"background-color: rgb(172, 172, 172);")
        self.pushBt_reset_10.setObjectName("pushBt_reset_10")
        self.horizontalLayout_24.addWidget(self.pushBt_reset_10)
        self.pushBt_cntinu_10 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.pushBt_cntinu_10.setFont(font)
        self.pushBt_cntinu_10.setStyleSheet("background-color: rgb(172, 172, 172);")
        self.pushBt_cntinu_10.setObjectName("pushBt_cntinu_10")
        self.horizontalLayout_24.addWidget(self.pushBt_cntinu_10)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 12)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 3)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_4.setText(_translate("MainWindow", "甲状腺超声图像智能识别与分类系统"))
        self.label_imNum_10.setText(_translate("MainWindow", "图像总数："))
        self.label_i_10.setText(_translate("MainWindow", "处理第 张："))
        self.label_res_10.setText(_translate("MainWindow", "预测结果："))
        self.pushBt_up_10.setText(_translate("MainWindow", "上一张"))
        self.pushBt_dwn_10.setText(_translate("MainWindow", "下一张"))
        self.pushBt_reset_10.setText(_translate("MainWindow", "重新开始"))
        self.pushBt_cntinu_10.setText(_translate("MainWindow", "继续"))

